//! Core data types for the Alpha Engine

use serde::{Deserialize, Serialize};

/// Trade signal generated by the alpha engine
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradeSignal {
    pub symbol: String,
    pub side: TradeSide,
    pub price: f64,
    pub size: f64,
    pub stop_loss: f64,
    pub take_profit: f64,
    pub time_to_live: u64, // milliseconds
    pub confidence: f64, // 0.0 to 1.0
    pub timestamp: u64,
}

/// Trade side enumeration
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum TradeSide {
    Buy,
    Sell,
}

/// Order book level
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderBookLevel {
    pub price: f64,
    pub quantity: f64,
}

/// Simplified order book snapshot
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderBookSnapshot {
    pub symbol: String,
    pub bids: Vec<OrderBookLevel>,
    pub asks: Vec<OrderBookLevel>,
    pub timestamp: u64,
}

/// Aggregated trade
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AggTrade {
    pub symbol: String,
    pub price: f64,
    pub quantity: f64,
    pub is_buyer_maker: bool,
    pub timestamp: u64,
}

/// Market data event
#[derive(Debug, Clone)]
pub enum MarketDataEvent {
    OrderBookUpdate(OrderBookSnapshot),
    AggTrade(AggTrade),
}

/// Wallet balance information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WalletBalance {
    pub equity: f64,
    pub available: f64,
    pub currency: String,
}

/// Position sizing parameters
#[derive(Debug, Clone)]
pub struct PositionSizingParams {
    pub risk_percent: f64, // percentage of equity to risk
    pub min_position_value: f64, // minimum position value in USD
    pub max_position_value: f64, // maximum position value in USD
}

/// Signal state machine states
#[derive(Debug, Clone, PartialEq)]
pub enum SignalState {
    Idle,
    Armed,
    Executing,
    Managing,
}

/// Trade intent to be sent to execution layer
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradeIntent {
    pub symbol: String,
    pub side: TradeSide,
    pub price: f64,
    pub size: f64,
    pub stop_loss: f64,
    pub take_profit: f64,
    pub time_to_live: u64, // milliseconds
    pub timestamp: u64,
}